### ISSUE TITLE
Try out SDK v6.0.0-alpha1 in Firely Server

### ISSUE THREAD

**Issue by alexzautke** [FirelyTeam/firely-net-sdk#3009]

**Comment by andrzejskowronski** [comment]
Blocking:
Both legacy Validator and the new one refer to 5.11, and won't work with 6.0.0. Either/both need to be adjusted for 6.0.0 to proceed.

Changes that were needed:
- `ElementNodeExtensions.ToScopedNode` changed return to `IScopedNode`, so any code that relied on concrete type needed to be adjusted, either with upcasting, or wrapping in ScopedNode, but that has some side-effects (losing fullUrl, Parent)
- `Base` no longer implements `IReadOnlyDictionary<string, object>` causing collection initializers to fail. Example below no longer compiles with error that the type does not implement `IEnumerable`
	- `new Parameters {{"rawResult", new FhirString(json)}};`
- `SearchParamType` moved namespaces, which led to conflicts with FS copy of the enum
- `SearchParamDefinition` moved namespace, needed to fix references
- [In this test](https://github.com/FirelyTeam/Vonk/blob/54566967a23eeec00bbadc7ab89af4a99e92f82c/test/Vonk.Core.Tests/ElementModel/BundleBuildingTests.cs#L178), the second ShortPath is equal to Location now as it fails on [this behaviour](https://github.com/FirelyTeam/firely-net-sdk/blob/c5e4d28fa2dc0cb9d9d96b1f6deefb35e905b4ad/src/Hl7.Fhir.Base/ElementModel/ScopedNode.cs#L293) - if it would rather check for `IShortPathGenerator` it would work as expected
- `SourceNode.Valued` and `SourceNode.Resource` changed nullability, so some calls needed `!`
- `FhirTypeAttribute.IsResource` removed, some logic needed to be adjusted for that
- `Base.NamedChildren` removed, replaced with `EnumerateElements` for the same behaviour
- `FhirJsonSerializationSettings` gone from `ITypedElement.ToJson`

**Comment by ewoutkramer** [comment]
I've turned this list into a todo for finishing up the alpha-2 release here: https://github.com/FirelyTeam/firely-net-sdk/issues/3029, so we can consider this current task done.
